blank_issues_enabled: false

contact_links:
  - name: ğŸ“– Documentation de TPI
    url: https://github.com/Yarkis01/TPI_Toolbox/blob/059a865d9d85a77d3f6f92be4fce6d35fb1fd932/README.md
    about: Consultez notre guide d'utilisation avant d'ouvrir un ticket.
  - name: ğŸš€ SuggÃ©rer une fonctionnalitÃ©
    url: https://github.com/Yarkis01/TPI_Toolbox/issues/new?assignees=&labels=enhancement&title=%5BFEATURE%5D+
    about: Proposez une nouvelle fonctionnalitÃ© ou une idÃ©e d'amÃ©lioration pour TPI.